services:
  bbaas-cdp-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: bbaas-cdp:local
    ports:
      - "8080:8080"
    network_mode: "host"
    environment:
      CDP_BIND_HOST: "127.0.0.1"
      # CDP_PUBLIC_HOST: "bbaas-browser-manager.b8z.me"
      CDP_PUBLIC_HOST: "localhost"
      CDP_PORT_MIN: "20000"
      CDP_PORT_MAX: "29999"
      BROWSER_IDLE_TIMEOUT: "1m"
      TASK_WORKER_CONCURRENCY: "1"
      TASK_LOG_PATH: "./logs"
      TASK_DB_PATH: "./tasks.db"
      PLAYWRIGHT_HEADLESS: "true"
